# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(765, 527)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 10, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.labelRetorno = QtWidgets.QLabel(self.centralwidget)
        self.labelRetorno.setGeometry(QtCore.QRect(50, 220, 641, 161))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelRetorno.setFont(font)
        self.labelRetorno.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelRetorno.setObjectName("labelRetorno")
        self.totalAtleta = QtWidgets.QPushButton(self.centralwidget)
        self.totalAtleta.setGeometry(QtCore.QRect(50, 60, 151, 23))
        self.totalAtleta.setObjectName("totalAtleta")
        self.totalPaticipates = QtWidgets.QPushButton(self.centralwidget)
        self.totalPaticipates.setGeometry(QtCore.QRect(210, 60, 151, 23))
        self.totalPaticipates.setObjectName("totalPaticipates")
        self.totalFeminino = QtWidgets.QPushButton(self.centralwidget)
        self.totalFeminino.setGeometry(QtCore.QRect(370, 60, 151, 23))
        self.totalFeminino.setObjectName("totalFeminino")
        self.totalMedalha = QtWidgets.QPushButton(self.centralwidget)
        self.totalMedalha.setGeometry(QtCore.QRect(540, 60, 151, 23))
        self.totalMedalha.setObjectName("totalMedalha")
        self.ranking = QtWidgets.QPushButton(self.centralwidget)
        self.ranking.setGeometry(QtCore.QRect(210, 90, 151, 23))
        self.ranking.setObjectName("ranking")
        self.totalMedalhapa = QtWidgets.QPushButton(self.centralwidget)
        self.totalMedalhapa.setGeometry(QtCore.QRect(50, 90, 151, 23))
        self.totalMedalhapa.setObjectName("totalMedalhapa")
        self.paisMais = QtWidgets.QPushButton(self.centralwidget)
        self.paisMais.setGeometry(QtCore.QRect(370, 90, 151, 23))
        self.paisMais.setObjectName("paisMais")
        self.paisMenos = QtWidgets.QPushButton(self.centralwidget)
        self.paisMenos.setGeometry(QtCore.QRect(540, 90, 151, 23))
        self.paisMenos.setObjectName("paisMenos")
        self.quantidadeTime = QtWidgets.QPushButton(self.centralwidget)
        self.quantidadeTime.setGeometry(QtCore.QRect(540, 120, 151, 23))
        self.quantidadeTime.setObjectName("quantidadeTime")
        self.totalAtletaa = QtWidgets.QPushButton(self.centralwidget)
        self.totalAtletaa.setGeometry(QtCore.QRect(210, 120, 151, 23))
        self.totalAtletaa.setObjectName("totalAtletaa")
        self.quantiEsport = QtWidgets.QPushButton(self.centralwidget)
        self.quantiEsport.setGeometry(QtCore.QRect(50, 120, 151, 23))
        self.quantiEsport.setObjectName("quantiEsport")
        self.totalTreina = QtWidgets.QPushButton(self.centralwidget)
        self.totalTreina.setGeometry(QtCore.QRect(370, 120, 151, 23))
        self.totalTreina.setObjectName("totalTreina")
        self.timePais = QtWidgets.QPushButton(self.centralwidget)
        self.timePais.setGeometry(QtCore.QRect(50, 150, 151, 23))
        self.timePais.setObjectName("timePais")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analise de dados"))
        self.label.setText(_translate("MainWindow", "Analise Das Olimpiadas"))
        self.labelRetorno.setText(_translate("MainWindow", "dsd"))
        self.totalAtleta.setText(_translate("MainWindow", "Total de atleta do mundo"))
        self.totalPaticipates.setText(_translate("MainWindow", "Total Paticipantes Masculino"))
        self.totalFeminino.setText(_translate("MainWindow", "Total Paticipantes Feminino"))
        self.totalMedalha.setText(_translate("MainWindow", "Total Medalhas Por Esporte"))
        self.ranking.setText(_translate("MainWindow", "Ranking Por Medalhas"))
        self.totalMedalhapa.setText(_translate("MainWindow", "Total De Medalhas Por Pais"))
        self.paisMais.setText(_translate("MainWindow", "Paises Com Mais Medalhas"))
        self.paisMenos.setText(_translate("MainWindow", "Paises Com Menos Medalhas"))
        self.quantidadeTime.setText(_translate("MainWindow", "Quantidade de Times"))
        self.totalAtletaa.setText(_translate("MainWindow", "Tipo Espote Para M e F"))
        self.quantiEsport.setText(_translate("MainWindow", "Quantidade Por Esporte"))
        self.totalTreina.setText(_translate("MainWindow", "Total de treinadores "))
        self.timePais.setText(_translate("MainWindow", "Times Por Pais"))
